### ISSUE TITLE
server won't start if cfengine name ends with an @

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#10]
See the following output from CommandBox that shows the inputs to runwar as well as the error that occurs.  I assume there is some faulty logic that assumes there will be text afte the `@` sign.

```
 Error invoking external process 2016-05-04 14:14:48 WARN RunwarLogger no attach in java.library.path
 ******************************************************************************
 Starting - port:13925 stop-port:13926 warpath:file:/C:/sandbox/servertest/
 context: /  -  version: 3.4.2
 web-dirs: C:\sandbox\servertest
 Log Directory: C:\Users\Brad.development\.CommandBox\server\A67FBAF285C230289F28F793CA23133C-servertest\lucee-cf-engine-4.5.2.018\logs
 ******************************************************************************
 Exception in thread "main" java.lang.ClassNotFoundException: lucee@.loader.servlet.CFMLServlet
 at java.net.URLClassLoader.findClass(Unknown Source)
 at java.lang.ClassLoader.loadClass(Unknown Source)
 at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
 at java.lang.ClassLoader.loadClass(Unknown Source)
 at runwar.Server.startServer(Server.java:359)
 ******************************************************************************
 *** stopping server
 *** server did not appear to be running
 ******************************************************************************

 "C:\Program Files\Java\jre1.8.0_73\bin\java.exe"
   -Xmx512m
   -Xms512m
   -javaagent:"C:\Users\Brad.development\.CommandBox/lib/lucee-inst.jar"
   -jar "C:\Users\Brad.development\.CommandBox\lib\runwar-3.4.2.jar"
   --background=true
   --port 13925
   --host 127.0.0.1
   --debug=false
   --stop-port 13926
   --processname "servertest [lucee@]"
   --log-dir "C:\Users\Brad.development\.CommandBox/server/A67FBAF285C230289F28F793CA23133C-servertest/lucee-cf-engine-4.5.2.018/logs"
   --open-browser true
   --open-url http://127.0.0.1:13925
   --cfengine-name lucee@
   --server-name "servertest"
   --tray-icon "C:\Users\Brad.development\.CommandBox/lib/trayicon.png"
   --tray-config "C:\Users\Brad.development\.CommandBox/lib/traymenu-lucee.json"
   --directoryindex "true"
   --cfml-web-config "C:\Users\Brad.development\.CommandBox/server/A67FBAF285C230289F28F793CA23133C-servertest/lucee-cf-engine-4.5.2.018"
   --cfml-server-config "C:\Users\Brad.development\.CommandBox/engine/cfml/server/"
   -war "C:\sandbox\servertest"
   --lib-dirs "C:\Users\Brad.development\.CommandBox/lib"
   --urlrewrite-enable false```

**Comment by denuno** [comment]
The only valid cfengine-name options are lucee, adobe, or railo... lucee@ just isn't valid, we'll need to catch that on the CommandBox side.

**Comment by denuno** [comment]
I did add a check in runwar so it'll be a more informative error if that happens.

**Comment by bdw429s** [comment]
I already changed it on the CommandBox side, but I'm not sure how it was ever working before.

**Comment by denuno** [comment]
Pretty sure we had it hard-coded to lucee-- I don't think we needed to change the engine name since we changed it from railo, back before multi-engine support.

**Comment by bdw429s** [comment]
Yeah, it used to be hard-coded to lucee before multi-engine.  Sorry, I mean I couldn't figure out how it worked from your original pull.  Dunno, so many variables got re-arranged I lost track.  Do I need to pass in the engine name for standalone servers, or only for the embedded one?

**Comment by denuno** [comment]
I was just doing a listFirst(engineName,"@") I think.  

Right now engineName doesn't really matter except for the embedded server, but we should pass it in regardless, as eventually I'll clean stuff up (only need to check for CFIDE on adobe, for instance, which will speed up the resource lookup by 000000001% ;]).
