### ISSUE TITLE
3.8.0 snapshot errors on Adobe CF11 engine

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#105]
After upgrading to the 3.8.0 snapshot, one of my local CF11 sites stopped working.  With errors in the logs such as these:

```
Mar 19, 2018 14:50:56 PM Error [XNIO-1 task-18] - Unable to read web.xml
```

```
Exception thrown by error-handling template:
java.io.FileNotFoundException: D:\webroot\WEB-INF\cftags
        at coldfusion.jsp.JRunTagLibraryInfo.resolveTagLibraryTLD(JRunTagLibraryInfo.java:454)
        at coldfusion.jsp.JRunTagLibraryInfo.<init>(JRunTagLibraryInfo.java:220)
        at coldfusion.jsp.JRunTagLibraryInfo.lookupTLI(JRunTagLibraryInfo.java:128)
        at coldfusion.compiler.NeoTranslator.<init>(NeoTranslator.java:99)
        at coldfusion.runtime.TemplateClassLoader.findClass(TemplateClassLoader.java:634)
        at coldfusion.filter.PathFilter.invoke(PathFilter.java:138)
        at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
        at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
        at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
        at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
        at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)
        at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
        at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
        at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
        at coldfusion.CfmServlet.service(CfmServlet.java:219)
        at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
```

:point_up:  The `D:\webroot\WEB-INF` path above is NOT the correct path to the web-inf.  In fact, that folder doesn't even exist.  It should be pointing to the CommandBox server home.  Something seems to have changed in the handling of the WEB-INF for Adobe servers.

**Comment by gpickin** [comment]
Simple issue for rewrite files, posting as a separate issue

**Comment by bdw429s** [comment]
Adobe engines are still totally broken in the latest 3.8 snapshot.  Trying to start a 2016 server with
```
start cfengine=adobe
```
gives me this:
```
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
    at java.io.WinNTFileSystem.canonicalize0(Native Method)
    at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
    at java.io.File.getCanonicalPath(File.java:618)
    at java.io.File.getCanonicalFile(File.java:643)
    at coldfusion.bootstrap.ClassloaderHelper._getClassLoader(ClassloaderHelper.java:290)
    at coldfusion.bootstrap.ClassloaderHelper.getClassLoader(ClassloaderHelper.java:210)
    at coldfusion.bootstrap.ClassloaderHelper.initServletClass(ClassloaderHelper.java:118)
    at coldfusion.bootstrap.BootstrapServlet.init(BootstrapServlet.java:59)
    at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
    at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:300)
    at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:140)
    at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:565)
    at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:536)
    at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
    at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
    at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:578)
    at runwar.Server.startServer(Server.java:519)
    at runwar.Start.main(Start.java:128)

            \WEB-INF\cfusion\lib\updates: directory does not exist, hotfixes cannot be applied
java.lang.ClassNotFoundException: coldfusion.server.j2ee.CFStartUpServlet
    at coldfusion.bootstrap.BootstrapClassLoader.loadClass(BootstrapClassLoader.java:252)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at coldfusion.bootstrap.ClassloaderHelper.initServletClass(ClassloaderHelper.java:120)
    at coldfusion.bootstrap.BootstrapServlet.init(BootstrapServlet.java:59)
    at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
    at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:300)
    at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:140)
    at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:565)
    at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:536)
    at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
    at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
    at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:578)
    at runwar.Server.startServer(Server.java:519)
    at runwar.Start.main(Start.java:128)
```

**Comment by bdw429s** [comment]
At first glance, Adobe seems to be working again on 3.8.1.
