### ISSUE TITLE
Server won't start with $ in web root path

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#107]
Ran across this a few months ago in CommandBox and put in a JIRA ticket but forgot to create one here as well.

```
java.lang.IllegalArgumentException: Illegal group reference
        at java.util.regex.Matcher.appendReplacement(Unknown Source)
        at java.util.regex.Matcher.replaceAll(Unknown Source)
        at java.lang.String.replaceAll(Unknown Source)
        at runwar.undertow.WebXMLParser.parseWebXml(WebXMLParser.java:283)
        at runwar.Server.startServer(Server.java:498)
        at runwar.Start.main(Start.java:108)
2018-03-21 23:17:45 ERROR RunwarLogger Error reading web.xml
java.lang.IllegalArgumentException: Illegal group reference
        at java.util.regex.Matcher.appendReplacement(Unknown Source)
        at java.util.regex.Matcher.replaceAll(Unknown Source)
        at java.lang.String.replaceAll(Unknown Source)
        at runwar.undertow.WebXMLParser.parseWebXml(WebXMLParser.java:283)
        at runwar.Server.startServer(Server.java:498)
        at runwar.Start.main(Start.java:108)
```

**Comment by denuno** [comment]
Should be fixed in latest snapshot.

**Comment by bdw429s** [comment]
First test seems to work good

**Comment by bdw429s** [comment]
https://ortussolutions.atlassian.net/browse/COMMANDBOX-749
