### ISSUE TITLE
/CFIDE doesn't work on Adobe servers

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#120]
`/CFIDE` doesn't work so I can't hit the administrator
 ```js
} else if (path.startsWith("/CFIDE")) {
                reqFile = new File(WEBINF.getParentFile(), path);
```
:point_up: That code in the mapped resource manager is supposed to handle it
But here's the trace logs:
```bash
[DEBUG] runwar.request: * requested:CFIDE/administrator/index.cfm
[TRACE] runwar.request: * checking with base path: D:\MonkeyMedia\CFIDE\administrator\index.cfm
[DEBUG] runwar.request: ** No mapped resource for: CFIDE/administrator/index.cfm (reqFile was:null)
```
The leading slash doesn't appear to be present
It's `CFIDE` instead of `/CFIDE` which I assume is preventing if from hitting the if statement above.
What would have caused that?

**Comment by denuno** [comment]
Hmm, that's actually working for me, and I switched to a regex matcher for that so slash or no slash it should find it...

**Comment by denuno** [comment]
I added a clean to the build, maybe it wasn't putting fresh artifacts out or some such, as like I said I switched to a regex a couple commits back.

**Comment by denuno** [comment]
Gonna close this as it looks like we're good to go with adobe again.

**Comment by bdw429s** [comment]
Nope, still having issues on my Windows box.  I can't reopen this ticket :/
I get a ColdFusion missing template exception when I try to hit the admin.
```
http://127.0.0.1:61711/CFIDE/administrator/enter.cfm
[DEBUG] runwar.request: * requested:CFIDE/administrator/enter.cfm
[TRACE] runwar.request: * checking with base path: C:\sandbox\test\CFIDE\administrator\enter.cfm
[DEBUG] runwar.request: ** No mapped resource for: CFIDE/administrator/enter.cfm (reqFile was:null)
[DEBUG] org.tuckey.web.filters.urlrewrite.utils.ServerNameMatcher: looking for hostname match on current server name 127.0.0.1
[DEBUG] org.tuckey.web.filters.urlrewrite.UrlRewriteFilter: checking for status path on /CFIDE/administrator/enter.cfm
[DEBUG] org.tuckey.web.filters.urlrewrite.UrlRewriter: processing request for /CFIDE/administrator/enter.cfm
[DEBUG] org.tuckey.web.filters.urlrewrite.RuleBase: Rule 0 run called with /CFIDE/administrator/enter.cfm
[DEBUG] org.tuckey.web.filters.urlrewrite.RuleBase: matched "from"
[DEBUG] org.tuckey.web.filters.urlrewrite.Condition: evaluating "/CFIDE/administrator/enter.cfm" against ^/(flex2gateway|flashservices/gateway|messagebroker|lucee|rest|cfide|CFIDE|cfformgateway|jrunscripts|cf_scripts)/.*
[TRACE] org.tuckey.web.filters.urlrewrite.Condition: outcome true
[DEBUG] org.tuckey.web.filters.urlrewrite.Condition: not equal operator in use
[DEBUG] org.tuckey.web.filters.urlrewrite.Condition: evaluating "/CFIDE/administrator/enter.cfm" against ^/tuckey-status
[TRACE] org.tuckey.web.filters.urlrewrite.Condition: outcome false
[DEBUG] org.tuckey.web.filters.urlrewrite.Condition: not equal operator in use
[DEBUG] org.tuckey.web.filters.urlrewrite.Condition: evaluating "/CFIDE/administrator/enter.cfm" against ^/favicon.ico
[TRACE] org.tuckey.web.filters.urlrewrite.Condition: outcome false
[DEBUG] org.tuckey.web.filters.urlrewrite.Condition: not equal operator in use
[DEBUG] org.tuckey.web.filters.urlrewrite.Condition: evaluating "/CFIDE/administrator/enter.cfm" against ^/.*\.cf(m|ml)/.*
[TRACE] org.tuckey.web.filters.urlrewrite.Condition: outcome false
[DEBUG] org.tuckey.web.filters.urlrewrite.Condition: not equal operator in use
[DEBUG] runwar.request: * requested:
[TRACE] runwar.request: * checking with base path: C:\sandbox\test
[DEBUG] runwar.request: ** path mapped to: C:\sandbox\test
[DEBUG] org.tuckey.web.filters.urlrewrite.Condition: fileName found is C:\sandbox\test\CFIDE\administrator\enter.cfm
[DEBUG] org.tuckey.web.filters.urlrewrite.Condition: checking to see if C:\sandbox\test\CFIDE\administrator\enter.cfm is not a directory
[TRACE] org.tuckey.web.filters.urlrewrite.Condition: outcome true
[DEBUG] org.tuckey.web.filters.urlrewrite.Condition: fileName found is C:\sandbox\test\CFIDE\administrator\enter.cfm
[DEBUG] org.tuckey.web.filters.urlrewrite.Condition: checking to see if C:\sandbox\test\CFIDE\administrator\enter.cfm is not a file
[TRACE] org.tuckey.web.filters.urlrewrite.Condition: outcome true
[DEBUG] org.tuckey.web.filters.urlrewrite.RuleBase: conditions do not match
Apr 6, 2018 21:44:44 PM Error [XNIO-1 task-3] - File not found: /CFIDE/administrator/enter.cfm The specific sequence of files included or processed is: C:\sandbox\test\CFIDE\administrator\enter.cfm''
[DEBUG] runwar.request: * requested:WEB-INF/exception/coldfusion/runtime/TemplateNotFoundException.cfm
```

**Comment by bdw429s** [comment]
Working a little, but still seeing errors in the logs related to the new regular expressions:

```
ErrorHandler handleRequest triggered
java.lang.StringIndexOutOfBoundsException: String index out of range: 51
        at java.lang.String.charAt(String.java:658)
        at java.lang.Character.codePointAt(Character.java:4866)
        at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
        at java.util.regex.Pattern$Curly.match0(Pattern.java:4262)
        at java.util.regex.Pattern$Curly.match0(Pattern.java:4265)
        at java.util.regex.Pattern$Curly.match(Pattern.java:4236)
        at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
        at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
        at java.util.regex.Pattern$Slice.match(Pattern.java:3974)
        at java.util.regex.Pattern$Ques.match(Pattern.java:4184)
        at java.util.regex.Pattern$Begin.match(Pattern.java:3527)
        at java.util.regex.Matcher.match(Matcher.java:1270)
        at java.util.regex.Matcher.matches(Matcher.java:604)
        at runwar.undertow.MappedResourceManager.getResource(MappedResourceManager.java:86)
        at io.undertow.server.handlers.resource.CachingResourceManager.getResource(CachingResourceManager.java:114)
        at io.undertow.server.handlers.resource.CachingResourceManager.getResource(CachingResourceManager.java:32)
        at io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(ServletPathMatches.java:96)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:151)
        at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:65)
        at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
        at runwar.Server$2.handleRequest(Server.java:598)
        at runwar.ErrorHandler.handleRequest(ErrorHandler.java:44)
        at io.undertow.server.handlers.accesslog.AccessLogHandler.handleRequest(AccessLogHandler.java:138)
        at io.undertow.server.handlers.ProxyPeerAddressHandler.handleRequest(ProxyPeerAddressHandler.java:103)
        at io.undertow.server.handlers.SSLHeaderHandler.handleRequest(SSLHeaderHandler.java:105)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
        at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
Location: /CFIDE/administrator/images/contentframetopright.png generated no content, maybe verify any errorPage locations? (status code: 200)
```
