### ISSUE TITLE
make welcome-file option override web.xml

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#42]
Make the following:

```
--welcome-files "go.cfm"
```

take precedence regardless of whether the war has a `web.xml`.

CommandBox sister ticket: https://ortussolutions.atlassian.net/browse/COMMANDBOX-473

**Comment by bdw429s** [comment]
Any update on this @denuno ?

**Comment by bdw429s** [comment]
Just bumped to the latest runwar and I've got an exception coming from the welcome file list change

```
Exception in thread "main" java.lang.NullPointerException
     [exec]   at java.util.Objects.requireNonNull(Objects.java:203)
     [exec]   at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
     [exec]   at java.util.Arrays.asList(Arrays.java:3800)
     [exec]   at io.undertow.servlet.api.DeploymentInfo.addWelcomePages(DeploymentInfo.java:501)
     [exec]   at runwar.Server.startServer(Server.java:400)
```

**Comment by bdw429s** [comment]
So best as I can tell-- welcome pages don't work at all for internal server regardless of whether I pass the `--welcome-files` param.  Welcome files work on WAR servers ONLY if I don't supply a setting and let it default.  If I set a custom welcome page, I just get a directory listing.

**Comment by bdw429s** [comment]
Any update on this @denuno ?  This feature seems DOA.

**Comment by bdw429s** [comment]
I think I have a fix here:
https://github.com/cfmlprojects/runwar/pull/50

**Comment by bdw429s** [comment]
Working in the latest snapshot BTW.
