### ISSUE TITLE
Stop adding Lucee java agent

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#55]
Runwar tries to dynamically load the java agent for even Adobe servers.  The java agent isn't even needed on Lucee 5 and I leave it off nowadays even on Lucee 4 due to serious performance issues that it has caused that remain unfixed.  (They were fixed in Lucee 5).  CommandBox takes are of adding the java agent when it's needed, so runwar doesn't need to do it at all.  If there is a non-CommandBox use for this, then let's add a config option.

**Comment by bdw429s** [comment]
Here is some of the debug output from starting an Adobe WAR file which shouldn't be doing anything with the Lucee java agent.

```
2016-12-26 11:58:03 DEBUG RunwarLogger Trying to load java agent from local jar file
2016-12-26 11:58:03 DEBUG RunwarLogger Trying first:D:\adobe\engine\WEB-INF\lib
2016-12-26 11:58:03 WARN RunwarLogger The agent loader was not found for auto-initialization
2016-12-26 11:58:03 DEBUG RunwarLogger Searching for java agent
2016-12-26 11:58:03 DEBUG RunwarLogger Trying to load java agent from classpath
2016-12-26 11:58:03 DEBUG RunwarLogger Trying to load java agent from jar containing this class
2016-12-26 11:58:03 DEBUG RunwarLogger Trying to load java agent from location of current class file
2016-12-26 11:58:03 DEBUG RunwarLogger Loading internal lucee agent from C:\Users\Brad.development\.CommandBox\lib\lucee-inst.jar
```

**Comment by bdw429s** [comment]
As a note, I don't think the java agent loading is actually even working on Lucee 5.  See this ticket: 
https://luceeserver.atlassian.net/browse/LDEV-1138
This error happens even though Runwar claims it has loaded a java agent.

**Comment by bdw429s** [comment]
As an additional note, it seems that Runwar's attempt to load the java agent is actually the cause of the Lucee ticket above.  Basically the list of attach providers is read from tools.jar ONCE when the first time that `com.sun.tools.attach.spi.AttachProvider.providers()` is called.  This happens inside runwar, but without a tools.jar in your classpath, the list of providers will be loaded as empty.
Later on when Lucee tracks down a tools.jar (it has jars for each OS embedded inside it just in case) and class loads it, it will be too late since the list of attach providers is already initialized. (edited)
The hierarchy of class paths are checked starting with the class loader for the attachprovider class, so even if I try to force a reload, the tools.jar will not be in any of the parent class loaders. (edited)
If I remove the `new AgentInitialization().loadAgentFromLocalJarFile();` call from Runwar and completely remove all the `sun.*` and `com.sun.*` classes from the runwar build, then Lucee 5 starts working again.
It is able to attach to the VM via the correct attach provider and load the agent.

I think this might be another reason to just remove this functionality from Runwar.

**Comment by bdw429s** [comment]
@denuno Pull for this:
https://github.com/cfmlprojects/runwar/pull/61

**Comment by timsayshey** [comment]
I am still getting the JavaAgent error in Docker on Windows 7.

To reproduce, run the following on Windows 7:
```
git clone https://github.com/timsayshey/wheelie.git
cd wheelie
docker-compose -f config/docker/local-mysql/docker-compose.yml up
```

![192 168 99 100-8080- 2](https://user-images.githubusercontent.com/1148940/29170968-685406f4-7da0-11e7-8554-956c97009979.png)

**Comment by bdw429s** [comment]
@timsayshey Can you show the exact version of Lucee that's being started, and confirm the version of CommandBox in use (or at least the version of the Docker image)?  I haven't seen that error in quite some time.  Unfortunately, the error you pasted above is not helpful at all, but it's not your fault.  When Lucee can't load the java agent, it glosses over the error and allows the page load to go on down the line until it errors later on while trying to use the agent.  This is not helpful since instead of getting the actual source error, we just get a "hey, it didn't work" quality of message.  Can you check all the server logs (the process out logs as well as the Lucee-specific logs) and see if there's more info in any of them.  I can' recall off the top of my head if there's logging in place.

**Comment by timsayshey** [comment]
@bdw429s Thanks Brad -- Here are the specific versions: Lucee 5.2.1+9 and ortussolutions/commandbox:latest

I'll see about getting the log files. I ssh'd in but I can't find the /root/serverHome directory.

**Comment by bdw429s** [comment]
Thanks for checking into the logs.  Also, you mentioned this was Windows 7.  Can you confirm, Windows 7 is the _host_ machine, right?  I've got Windows 7 so I'll give your image a try real quick as well.

**Comment by bdw429s** [comment]
I started up your container and I get the exact same error, even on Lucee 5.1.  I'm not really sure what's going on.  To be honest, I've mostly been using Lucee 4 with my docker tests, so I'm not 100% sure right off if this is a Lucee 5 issues, a regression in Runwar, or just something the matter with your image. We were getting this error a while back and it took many hours of troubleshooting but once we squashed it I hadn't seen this message again since.  I don't know when I'll have time to dig back into it.  Maybe @denuno can help look at it since it's so easily reproducible for me. 

Ok, and by the way, the "real" error is in the web context application log.  Of course, I'm not sure what it means right off.
```
"INFO","Thread-13","08/11/2017","03:47:09","","Instrumentation;Unable to open socket file: target process not responding or HotSpot VM not loaded;com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
        at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
        at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:213)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at lucee.runtime.instrumentation.InstrumentationFactory.loadAgent(InstrumentationFactory.java:335)
        at lucee.runtime.instrumentation.InstrumentationFactory.access$400(InstrumentationFactory.java:57)
        at lucee.runtime.instrumentation.InstrumentationFactory$1.run(InstrumentationFactory.java:113)
        at java.security.AccessController.doPrivileged(Native Method)
        at lucee.runtime.instrumentation.InstrumentationFactory.getInstrumentation(InstrumentationFactory.java:77)
        at lucee.commons.lang.PhysicalClassLoader.loadClass(PhysicalClassLoader.java:174)
        at lucee.runtime.MappingImpl.getPhysicalClass(MappingImpl.java:259)
        at lucee.runtime.PageSourceImpl._compile(PageSourceImpl.java:358)
        at lucee.runtime.PageSourceImpl.compile(PageSourceImpl.java:322)
        at lucee.runtime.PageSourceImpl.loadPhysical(PageSourceImpl.java:277)
        at lucee.runtime.PageSourceImpl.loadPage(PageSourceImpl.java:163)
        at lucee.runtime.component.ComponentLoader.loadComponent(ComponentLoader.java:364)
        at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:113)
        at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:43)
        at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2408)
        at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2398)
        at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2366)
        at lucee.runtime.engine.Request.run(Request.java:34)
```

**Comment by timsayshey** [comment]
Glad you were able to reproduce it. 

Should we reopen this ticket or make a new one?

I didn't think it was my image since I'm just using compose and pointing to the latest commandbox docker image:
https://github.com/timsayshey/wheelie/blob/release/config/docker/local-mysql/docker-compose.yml
https://github.com/timsayshey/wheelie/blob/release/server.json

Thanks again for looking into this.

**Comment by bdw429s** [comment]
I would create a new ticket since even though the symptom is the same, I've no clue what's causing it this time around.  The solution for this ticket was simply to rip out all the logic in Runwar that even messed with auto-loading the java agent since it was duplicating what Lucee already does, so I'm not sure if the issue could still even be in Lucee.  It's entirely possible that it's somehow related to classloaders and OSGI inside Lucee 5.  One of the reasons I say that is because I also found this error message in the logs which references a native library being loaded in two different classloaders.

```
"INFO","Thread-37","08/11/2017","03:48:29","","Instrumentation;Native Library /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libattach.so already loaded in another classloader;java.lang.UnsatisfiedLinkError: Native Library /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libattach.so already loaded
in another classloader
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1907)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at sun.tools.attach.LinuxVirtualMachine.<clinit>(LinuxVirtualMachine.java:336)
        at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:213)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at lucee.runtime.instrumentation.InstrumentationFactory.loadAgent(InstrumentationFactory.java:335)
        at lucee.runtime.instrumentation.InstrumentationFactory.access$400(InstrumentationFactory.java:57)
        at lucee.runtime.instrumentation.InstrumentationFactory$1.run(InstrumentationFactory.java:113)
        at java.security.AccessController.doPrivileged(Native Method)
        at lucee.runtime.instrumentation.InstrumentationFactory.getInstrumentation(InstrumentationFactory.java:77)
        at lucee.commons.lang.PhysicalClassLoader.loadClass(PhysicalClassLoader.java:174)
        at lucee.runtime.MappingImpl.getPhysicalClass(MappingImpl.java:259)
        at lucee.runtime.PageSourceImpl._compile(PageSourceImpl.java:358)
        at lucee.runtime.PageSourceImpl.compile(PageSourceImpl.java:322)
        at lucee.runtime.PageSourceImpl.loadPhysical(PageSourceImpl.java:277)
        at lucee.runtime.PageSourceImpl.loadPageThrowTemplateException(PageSourceImpl.java:182)
        at lucee.runtime.PageSourceImpl.loadPage(PageSourceImpl.java:905)
        at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:923)
        at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:842)
        at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:826)
        at config.app_cfm$cf.call(/config/app.cfm:2)
        at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:928)
        at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:842)
        at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:826)
```

**Comment by bdw429s** [comment]
@denuno Read the accepted answer on this SO post. Do you think it applies here?  I know we have several layers of classloading going on, but I have no idea how to track down what's getting loaded and where.

https://stackoverflow.com/questions/36936948/java-lang-unsatisfiedlinkerror-native-library-xxx-so-already-loaded-in-another

**Comment by timsayshey** [comment]
☝️

**Comment by denuno** [comment]
That is odd.  Does this only happen on Windows 7?  Latest JRE?

**Comment by timsayshey** [comment]
Yes, my discussion with Brad seemed to indicate that it works for Windows 10 with the newer Docker app. In my case, I only have Windows 7 machines to test with so I can't confirm whether it affects any other OSes. And yes, I was using the latest JRE. 

To test, run Windows 7 with Docker and run the following command:
```
git clone https://github.com/timsayshey/wheelie.git
cd wheelie
docker-compose -f config/docker/local-mysql/docker-compose.yml up
```

This should reproduce the error for you.

**Comment by denuno** [comment]
Hmm, frankly it's going to be hard to get around to fixing this one, I think that might have been part of why I had that code we ripped out in there to begin with, but it conflicted with the newer stuff as demonstrated by this ticket...  You could maybe try using an older version of runwar, pre-agent-loading-removal, and see if that works.  Lucee 5 itself runs fine outside of cmdbox/runwar for you, right?

**Comment by bdw429s** [comment]
I wouldn't be sure that the issue is Runwar specific.  There's someone else claiming to be seeing this on a regular Tomcat install of Lucee 5 in the comments of this ticket:
https://luceeserver.atlassian.net/browse/LDEV-1138
The core of the problem that both this Tim B and Tim Clarke are having is 
> Native Library /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libattach.so already loaded in another classloader
but I don't know how to troubleshoot that.

**Comment by denuno** [comment]
Yeah, the link you posted had a system property that might be something to play with, but it'd have to be randomized somewhere, and I'm not sure where.  Might be worth trying an alternate JRE (OpenJDK if on Oracle, and vice versa)... totally apropos to nothing, the JDK is apparently going to be switching to a new "every X months" release schedule, and making OpenJDK and Oracle exactly the same (versus the just really really close as of the latest releases).
