### ISSUE TITLE
System tray hook erroring for some users

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#67]
Ok, only one user actually-- but it did prevent the entire server from starting.  The user was on Windows 10 x64 Pro and this showed up in this logs, aborting the server start.

```
Exception in thread "main" java.lang.RuntimeException: Event dispatch queue took longer than 2 seconds to complete. Please adjust `SystemTray.TIMEOUT` to a value which better suites your environment.
        at dorkbox.systemTray.SystemTray.updateMenuEntry_Enabled(SystemTray.java:777)
        at runwar.LaunchUtil.hookTray(LaunchUtil.java:344)
        at runwar.Server.startServer(Server.java:623)
        at runwar.Start.main(Start.java:12)
```

The internet is devoid of all information regarding this exception, so I'm sending a pull to wrap the tray hook in a try/catch and log the error if it happens, but still allow the server to finish starting.

**Comment by bdw429s** [comment]
https://github.com/cfmlprojects/runwar/pull/68

**Comment by bdw429s** [comment]
@denuno Here is the pull:
https://github.com/cfmlprojects/runwar/pull/68
