### ISSUE TITLE
Adobe servers no longer start on 3.6.1-SNAPSHOT

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#88]
I get this error when starting up Adobe CF 11 or 2016.   This is a major blocker right now in the CommandBox snapshot builds!

I think it's related to a version of Log4J that might have been bumped.  The line doing the logging is actually part of Undertow and has been that way for a couple years!  

```
java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2519)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2927)
        at org.jboss.logging.Slf4jLocationAwareLogger.doLogf(Slf4jLocationAwareLogger.java:81)
        at org.jboss.logging.Logger.logf(Logger.java:2445)
        at org.jboss.logging.DelegatingBasicLogger.debugf(DelegatingBasicLogger.java:364)
        at io.undertow.server.handlers.resource.PathResourceManager.getResource(PathResourceManager.java:216)
        at runwar.undertow.MappedResourceManager.getResource(MappedResourceManager.java:101)
        at io.undertow.server.handlers.resource.CachingResourceManager.getResource(CachingResourceManager.java:107)
        at io.undertow.server.handlers.resource.CachingResourceManager.getResource(CachingResourceManager.java:32)
        at io.undertow.servlet.spec.ServletContextImpl.getRealPath(ServletContextImpl.java:381)
        at flex.compiler.MxmlServlet.resolvePath(MxmlServlet.java:123)
        at flex.compiler.MxmlServlet.init(MxmlServlet.java:90)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at coldfusion.bootstrap.ClassloaderHelper.initServletClass(ClassloaderHelper.java:121)
        at coldfusion.bootstrap.BootstrapServlet.init(BootstrapServlet.java:59)
        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
        at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:250)
        at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:133)
        at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:558)
        at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:529)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:571)
        at runwar.Server.startServer(Server.java:603)
        at runwar.Start.main(Start.java:108)
```

**Comment by bdw429s** [comment]
This was fixed by rolling back some logging library changes.
